const commonjs = require('rollup-plugin-commonjs');
const license = require('rollup-plugin-license');

module.exports = {
  input: 'src/marked.js',
  output: {
    file: 'lib/marked.esm.js',
    format: 'esm'
  },
  plugins: [
    license({
      banner: `
DO NOT EDIT THIS FILE 不要编辑此文件
The code in this file is generated from files in ./src/
此代码是由 ./src/ 目录文件生成
`
    }),
    license({
      banner: `
@ektx/marked - a markdown parser
Copyright (c) 2011-${new Date().getFullYear()}, ektx. (MIT Licensed)
https://github.com/ektx/marked
`
    }),
    commonjs()
  ]
};
